"""Sphinx directive for pre-rendered guide snippet outputs."""

from pathlib import Path
from typing import ClassVar

from docutils import nodes
from docutils.parsers.rst import directives
from sphinx.util.docutils import SphinxDirective


class GuideResultDirective(SphinxDirective):
    """Embed stdout and optional figures generated by ``render_guide_outputs.py``."""

    required_arguments = 1
    optional_arguments = 0
    has_content = False
    option_spec: ClassVar[dict[str, object]] = {
        "caption": directives.unchanged,
        "figure": directives.flag,
        "alt": directives.unchanged,
    }

    def run(self) -> list[nodes.Node]:
        snippet_id = self.arguments[0]
        output_dir = Path(self.env.app.srcdir) / "_static" / "guide_outputs"
        caption = self.options.get("caption", "Output")
        alt_text = self.options.get("alt", f"Rendered result for {snippet_id}")
        show_figure = "figure" in self.options

        text_path = output_dir / f"{snippet_id}.txt"
        image_path = output_dir / f"{snippet_id}.png"
        if not text_path.is_file() and not (show_figure and image_path.is_file()):
            return [
                self.state.document.reporter.warning(
                    f"missing guide output for {snippet_id!r}; "
                    "run render_guide_outputs.py",
                )
            ]

        body: list[nodes.Node] = []
        if text_path.is_file():
            content = text_path.read_text(encoding="utf-8").rstrip() + "\n"
            literal = nodes.literal_block(content, content)
            literal["language"] = "text"
            body.append(literal)

        if show_figure and image_path.is_file():
            image = nodes.image(
                uri=f"/_static/guide_outputs/{snippet_id}.png",
                alt=alt_text,
            )
            image["classes"] = ["guide-result-figure"]
            body.append(image)

        container = nodes.container("")
        container["classes"] = ["guide-result"]
        if body:
            title = nodes.paragraph("", "")
            title += nodes.strong("", caption)
            container += title
            container += body
        return [container]


def setup(app: object) -> dict[str, object]:
    """Register the guide-result directive."""
    app.add_directive("guide-result", GuideResultDirective)
    return {"version": "1.0", "parallel_read_safe": True, "parallel_write_safe": True}
